### ISSUE TITLE
这个软件的用法？

### ISSUE THREAD

**Issue by GD-HBX** [fqrouter/fqrouter#105]
是不是要相应的路由匹配一起使用的？我的路由是tp-link WR841N 8.0 ,手机装上了软件之后就是用不了！

**Comment by fqrouter** [comment]
现在fqrouter实现了的功能就是启动之后会在后台运行，它会帮你去干扰GFW。
保持fqrouter在后台运行，使用浏览器可以访问
vimeo.com
www.youtube.com
www.facebook.com
之类的网站而不被GFW重置连接。如果你知道之前一个叫西厢计划的东西，fqrouter和它的作用类似
但是由于不少网站的ip也被封了，所以使用体验上来说还不是特别好。
使用这个功能只需要点击start按钮就可以了。

另外一个正在开发中的功能是启动无线中继。这个是把你的手机变成无线路由器的功能。
手机自身可以连接着无线网，“同时”启动另外一个无线网共享给其他的设备。
这些无线设备连接进来之后也可以受到fqrouter的帮助，去干扰GFW。
所以vimeo.com应该也是可以上的。
使用这个功能除了点击start按钮之外，还需要点击manage按钮，在打开的浏览器中点击start wifi hotspot

**Comment by fqrouter** [comment]
new ui should be a lot more self-explanatory
