### ISSUE TITLE
Nexus 4当在web界面点击启动热点时手机重启，系统ROM为官方工厂镜像4.2.2

### ISSUE THREAD

**Issue by x2c3z4** [fqrouter/fqrouter#108]

**Comment by fqrouter** [comment]
可以用report error给我发一份日志吗？

**Comment by x2c3z4** [comment]
ok,发了，不知道对不对。

冯力

发件人： Qin Fen
发送时间： 2013-04-05 16:04
收件人： fqrouter/fqrouter
抄送： vonnyfly
主题： Re: [fqrouter] Nexus 4当在web界面点击启动热点时手机重启，系统ROM为官方工厂镜像4.2.2 (#108)
可以用report error给我发一份日志吗？

**Comment by fqrouter** [comment]
非常有帮助， 感谢！

2013/4/5 vonnyfly notifications@github.com

**Comment by fqrouter** [comment]
fixed
