### ISSUE TITLE
Android 上调用 shell 的权限问题

### ISSUE THREAD

**Issue by liruqi** [fqrouter/fqrouter#109]
04-05 18:55:23.300: D/fqrouter(2546): shell: chmod: /data/data/fq.router/python/bin/python: Operation not permitted
04-05 18:55:23.300: E/fqrouter(2546): failed to make payload executable
04-05 18:55:23.300: E/fqrouter(2546): java.lang.Exception: failed to execute: [chmod, 0700, /data/data/fq.router/python/bin/python], exit value: 1
04-05 18:55:23.300: E/fqrouter(2546):   at fq.router.utils.ShellUtils.waitFor(ShellUtils.java:67)
04-05 18:55:23.300: E/fqrouter(2546):   at fq.router.utils.ShellUtils.waitFor(ShellUtils.java:45)
04-05 18:55:23.300: E/fqrouter(2546):   at fq.router.utils.ShellUtils.execute(ShellUtils.java:17)
04-05 18:55:23.300: E/fqrouter(2546):   at fq.router.Deployer.chmod(Deployer.java:202)
04-05 18:55:23.300: E/fqrouter(2546):   at fq.router.Deployer.makePayloadExecutable(Deployer.java:185)
04-05 18:55:23.300: E/fqrouter(2546):   at fq.router.Deployer.deploy(Deployer.java:72)
04-05 18:55:23.300: E/fqrouter(2546):   at fq.router.Supervisor.run(Supervisor.java:46)
04-05 18:55:23.300: E/fqrouter(2546):   at java.lang.Thread.run(Thread.java:1019)

另外, 还有些跟环境相关的问题, 比如busybox 用不了之类.

这些准备工作, 不同固件差距挺大的. 我用的是desize z, CM 2.3 的固件. 貌似我用 python 脚本下载的 busybox 无法在手机上运行. chmod 路径也是代码hardcode 的路径.

当然这些问题对于开发者而言并不大, 表达清楚你的意图足够了.

**Comment by fqrouter** [comment]
你用report error给我发一个完整的错误日志吧。会这可以加我的gtalk，帐号是fqrouter xx gmail.com

**Comment by fqrouter** [comment]
use java code to set permission
execute python-launcher.sh using busybox sh
