### ISSUE TITLE
https://github.com/fqrouter/openwrt-trunk里的720n现在编译出错了，1个月前没问题

### ISSUE THREAD

**Issue by 38828** [fqrouter/fqrouter#150]
https://github.com/fqrouter/openwrt-trunk里的720n现在编译出错了，1个月前没问题。谢谢了

**Comment by fqrouter** [comment]
我很久没有弄720n了，你用官方的库自己改吧。

**Comment by 38828** [comment]
好的，谢谢了。有没有教程的

**Comment by fqrouter** [comment]
http://www.right.com.cn/forum/thread-100342-1-1.html
