### ISSUE TITLE
关于wifi的自动检测和切换

### ISSUE THREAD

**Issue by wayilive** [fqrouter/fqrouter#155]
hey，我是从你的博客搜索过来的，因为wp那边一直注册不了，我想问一下，如果我不用装你定制的固件，但又想实现功能，请问能如何利用、配置你的脚本呢？其实我的需求主要是：

1.家里的wifi、办公室的wifi、华为e5的3g路由，如何让703n在多个常用路由之间无缝的切换？当一个没信号时自动切到另一个？然后中继这些路由的信号？目前中继一个是可以了，但没办法自动切换……

2.在实现1的基础上，能不能划分vlan？一个用密码接入，可以翻墙，一个无密码，不能翻墙？或者是一个无线一个有线？

3.在1的基础上，当有wifi时，网口当lan口用，当没有wifi时，将703n的网口到有线网上，即可将有线网转为无线网？

我想第1个应该是能利用你的脚本来实现的，但请问需要加装什么软件包，和如何部署配置这些脚本呢（同时又不太想装luci）？谢谢！

**Comment by fqrouter** [comment]
我的脚本其实是一个hack，实际效果不咋的。
正确的做法是完全不用openwrt自带的脚本去做client模式的连接，自己用iw和wpa_supplicant命令去连接上级无线，但是这需要不少的脚本工作。
要在多个无线之间无缝工作是可以的，就是得自己写很多代码，openwrt自己的是不支持的。我的脚本也是一个hack，也不是工作很正常。
关键问题在于，openwrt定位于固定部署，所以不会把703n这样的设备的移动需求当作主要到特性来支持，所以对client模式的支持也是假定上级无线是固定不动的。
比较一下openwrt与android，你就会发现，android连接无线的代码是非常复杂的，就是因为要考虑到“移动”。
在openwrt上做一套完美的无线中继，支持移动需求，其实是一个比较大的工程。因为我已经把移动翻墙平台定为android手机了，所以703n的无线中继我就没有继续搞了。

不用分vlan，起两个无线就可以了。可以做，自己写代码。

网口在wan和lan也可以实现，自己写代码。

简单来说，你不是一个熟练的linux network 程序员，而且不打算投入一个月左右的业余时间，上述需求是没有戏到的。没有现成的脚本做这些工作的。

2013/4/25 wayilive notifications@github.com
