### ISSUE TITLE
发布到Google Play

### ISSUE THREAD

**Issue by zh99998** [fqrouter/fqrouter#200]
发布到Google Play安装和升级会方便不少喵...不用开未知来源和手动更新了...
如果没有开发者账号的话我可以免费提供....

**Comment by fqrouter** [comment]
有人把fq.router的package name给占了。我现在没法传到Google Play上去。

2013/6/18 zh99998 notifications@github.com

**Comment by fqrouter** [comment]
https://play.google.com/store/apps/details?id=fq.router2
