### ISSUE TITLE
代理状态页

### ISSUE THREAD

**Issue by fqrouter** [fqrouter/fqrouter#214]
代理列表
优先级
是否正在使用
上传字节数
下传字节数
总字节数
上传瞬时速度
下传瞬时速度
总瞬时速度

**Comment by skyred** [comment]
显示当前使用的代理方式 (一种或多种):

GoAgent Public
GoAgent Private
Shadowsocks Public
Shadowsocks Private
HTTP Proxy Public
Http Proxy Private
SSH Private
