### ISSUE TITLE
fqrouter 是不是很费流量？或者说跟那个什么 P2P 共享功能有关？

### ISSUE THREAD

**Issue by glacjay** [fqrouter/fqrouter#227]
我大概用了十天左右，不管在家还是在公司都有无线，只有很少的情况用移动数据，结果忽然发现流量不够了。查看手机中的「流量使用情况」，只有 ftrouter 用了六十多兆，其他程序没有超过一兆的。我在最近几天开了一个自己的 shadowsocks 帐号。不知道这是不是正常情况？还是跟那个 P2P 共享科学上网的功能有关？

**Comment by fqrouter** [comment]
P2P功能还没有实现
你可以把设置里自动检查twitter/youtube是否可以访问的选项给关掉，可以省一些流量。

2013/7/30 Jay True notifications@github.com

**Comment by glacjay** [comment]
等我下个月再试试吧。
