### ISSUE TITLE
新功能请求 dns 隧道

### ISSUE THREAD

**Issue by ptpt52** [fqrouter/fqrouter#277]
原理类时于 iodine
http://code.kryo.se/iodine/
1. 希望可以自己配置 iodine dns服务器
2. 可以进行免费wifi穿透，比如CMCC，即使没有帐号也可以通过dns隧道穿透，本人亲自验证成功的

**Comment by boris1993** [comment]
我只是fork了一下，请向原作者Qin Fen反映

**Comment by fqrouter** [comment]
优先级比较低，暂时不会支持
