### ISSUE TITLE
Sharing via Wi-Fi "Reversed USB tethering" Connection on Android phone

### ISSUE THREAD

**Issue by ghost** [fqrouter/fqrouter#280]
Hi, I'm just read description of your software, and read all of your features, and I have one question here... is it possible to share usb reverse tethered traffic by wi-fi ?

Clarification:
I have PC's which has internet (via ethernet port).
I would like to connect Android phone by USB.
and get internet from PC's (by USB) and share it to others (via Wi-Fi) ?

P.S. I see in feature list

> lan in => fqrouter => wifi out (some set-top box)

but this is not clear is it what I'm looking for right now, or not ?

Thank you.

**Comment by fqrouter** [comment]
It should work

**Comment by ghost** [comment]
Sorry but could you please clarify how exactly I can share "USB internet" from Android with other devices using wi-fi ? What should I select in fqrouter to achieve it?

P.S. "USB Internet" means internet which is forwarded from other computer to Android device by USB cabel.

Thanks.

**Comment by fqrouter** [comment]
try connect android mobile via usb first
http://forum.xda-developers.com/showthread.php?t=2287494

Then try start 3G hotspot from settings. If not working
Try wifi repeater from fqrouter
