### ISSUE TITLE
在有google play的设备上使用google play升级

### ISSUE THREAD

**Issue by zh99998** [fqrouter/fqrouter#281]
提示升级之后下载下来是个人野生apk怪怪的，还得特意打开未知来源来安装..测一下如果设备上有google play那么调用google play来更新更合适一些.. 至于play下载已经被墙了的问题，既然升级那么也已经有fqrouter了，而且play的说明里也有野生apk链

**Comment by fqrouter** [comment]
Google Play不允许发布带android:debuggable="true"标志的apk文件，而且下载链接已经被GFW定点清除了。Google Play上的版本不会再更新。
