### ISSUE TITLE
Allow indirect SSH port forwarding?

### ISSUE THREAD

**Issue by phoeagon** [fqrouter/fqrouter#290]
Say, if I want to connect to server A which would redirect my request to B, which basically works like:

`autossh -L clientport:server_B_IP:server_B_port serverA -p server_A`

Currently fqrouter only supports a `autossh -D port` like redirect...

(If you can tell me how to build fqrouter from source maybe I can implement this...

**Comment by zhaoweny** [comment]
I think you may need to log in on server_b, then use `screen` witch can run anything at background and create the tunnel to server_a. After that you can simply just connect to server_b.I think this will work well.

**Comment by phoeagon** [comment]
I know it works this way. But after all 'ssh' command has this switch so i
wonder if it's lots of trouble to implement it...

**Comment by zhaoweny** [comment]
I see. But once you try my way using screen, you may just forget all command, and it may never need to re-configure.(Unless server_b or server_a offline.) The tunnel between server_b  and server_a. will run at background on server_b.
1. You need to log in at server_b;
2. download screen 
3. run `screen` to create a new screen
4. use ssh to connect server_a
5. press Ctrl-A then d to detach screen session
6. then, log out
7. use fqrouter, and add your ssh tunnel.

My English is not very good... I hope you know what I am saying.

**Comment by lsyj** [comment]
冒昧问一句，为什么讲英语

**Comment by zhaoweny** [comment]
这对我来说是一个不错的练习机会，同时也是在尊重原 Issuer.

**Comment by phoeagon** [comment]
@lsyj 因为说中文经常遇到不知道怎么翻译的term。什么consistency durability之类的我都要像一会儿才知道中文叫什么。。。

**Comment by chenjunsheng** [comment]
o
