### ISSUE TITLE
请问让 android wift hotspot 能使用 proxy 的 iptables 规则在哪里?

### ISSUE THREAD

**Issue by txchen** [fqrouter/fqrouter#293]
请问一下关键代码在哪里? 想研究一下 谢谢!

**Comment by fqrouter** [comment]
DNS_RULES = [
    (
        {'target': 'ACCEPT', 'extra': 'mark match 0xcafe', 'optional':
True},
        ('nat', 'OUTPUT', '-m mark --mark 0xcafe -j ACCEPT')
    ), (
        {'target': 'DNAT', 'extra': 'udp dpt:53 to:10.1.2.3:12345'},
        ('nat', 'OUTPUT', '-p udp ! -s 10.1.2.3 --dport 53 -j DNAT
--to-destination 10.1.2.3:12345')
    ), (
        {'target': 'DNAT', 'extra': 'udp dpt:53 to:10.1.2.3:12345'},
        ('nat', 'PREROUTING', '-p udp ! -s 10.1.2.3 --dport 53 -j DNAT
--to-destination 10.1.2.3:12345')
    )]
SOCKS_RULES = [
    (
        {'target': 'DROP', 'extra': 'icmp type 5'},
        ('filter', 'OUTPUT', '-p icmp --icmp-type 5 -j DROP')
    ), (
        {'target': 'ACCEPT', 'destination': '127.0.0.1'},
        ('nat', 'OUTPUT', '-p tcp -d 127.0.0.1 -j ACCEPT')
    ), (
        {'target': 'DNAT', 'extra': 'to:10.1.2.3:12345'},
        ('nat', 'OUTPUT', '-p tcp ! -s 10.1.2.3 -j DNAT --to-destination
10.1.2.3:12345')
    ), (
        {'target': 'DNAT', 'extra': 'to:10.1.2.3:12345'},
        ('nat', 'PREROUTING', '-p tcp ! -s 10.1.2.3 -j DNAT
--to-destination 10.1.2.3:12345')
    )]

**Comment by txchen** [comment]
多谢!
